version: 0.1
phases:
  install:
    commands:
      - sudo apt-get install unzip
      # TODO is this really safe? someone could hijack their dns and pwn us
      - wget --nv https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip
      - unzip terraform_0.11.11_linux_amd64.zip
      - sudo mv terraform /usr/local/bin/
      - rm terraform_0.11.11_linux_amd64.zip
      - terraform --version
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run-script build
      - terraform workspace new $CODEBUILD_RESOLVED_SOURCE_VERSION
      - terraform apply -auto-approve
      - npm run-script integration-tests
  post_build:
    commands:
      - #terraform destroy
