version: 0.1
phases:
  install:
    commands:
      - sudo apt-get install terraform
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run-script build
      - terraform workspace new $CODEBUILD_RESOLVED_SOURCE_VERSION
      - terraform apply -auto-approve
      - npm run-script integration-tests
  post_build:
    commands:
      - #terraform destroy
